// src/components/chat/ChatInterface.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Button from '@/components/ui/button/Button.svelte';
  import { Send, Bot, User, Loader2, Heart, Music, Film, Book, Mic, MicOff, Volume2, VolumeX } from 'lucide-svelte';
  import { toastStore } from '@/lib/stores/toast';
  import { aiService, type ChatMessage, type AIResponse } from '@/lib/services/ai';
  import { userProfileService, type UserProfile } from '@/lib/services/userProfile';
  import { voiceService } from '@/lib/services/voice';
  import { authStore } from '@/lib/stores/auth';
  
  let messages: Array<{ id: string; text: string; sender: 'user' | 'bot'; timestamp: Date; recommendations?: any[] }> = [];
  let newMessage = '';
  let loading = false;
  let userProfile: UserProfile | null = null;
  let authState: any;
  let voiceEnabled = false;
  let isListening = false;
  let isSpeaking = false;
  
  authStore.subscribe(state => {
    authState = state;
  });
  
  onMount(async () => {
    // Add welcome message
    messages = [
      {
        id: '1',
        text: "Hello! I'm your AI taste companion. I can help you discover new music, movies, books, and more based on your preferences. What would you like to explore today?",
        sender: 'bot',
        timestamp: new Date()
      }
    ];
    
    // Load user profile if authenticated
    if (authState?.user) {
      userProfile = await userProfileService.getUserProfile(authState.user.id);
      if (!userProfile) {
        // Create profile if it doesn't exist
        userProfile = await userProfileService.createUserProfile(authState.user.id, authState.user.email);
      }
    }
    
    // Check voice support
    voiceEnabled = voiceService.isSupported();
  });
  
  async function sendMessage() {
    if (!newMessage.trim()) return;
    
    const userMessage = {
      id: Date.now().toString(),
      text: newMessage,
      sender: 'user' as const,
      timestamp: new Date()
    };
    
    messages = [...messages, userMessage];
    const messageText = newMessage;
    newMessage = '';
    loading = true;
    
    try {
      // Convert messages to AI service format
      const aiMessages: ChatMessage[] = messages.map(msg => ({
        role: msg.sender === 'user' ? 'user' : 'assistant',
        content: msg.text
      }));
      
      // Get AI response
      const aiResponse: AIResponse = await aiService.generateChatResponse(aiMessages, userProfile);
      
      // Add bot response
      const botMessage = {
        id: (Date.now() + 1).toString(),
        text: aiResponse.content,
        sender: 'bot' as const,
        timestamp: new Date(),
        recommendations: aiResponse.recommendations
      };
      
      messages = [...messages, botMessage];
      
      // Speak the response if voice is enabled
      if (voiceEnabled) {
        await voiceService.speak(aiResponse.content);
      }
      
      // If user is authenticated and there are recommendations, save them
      if (authState?.user && aiResponse.recommendations?.length) {
        for (const rec of aiResponse.recommendations) {
          const category = rec.type === 'music' ? 'music' : 
                          rec.type === 'movie' ? 'movies' : 
                          rec.type === 'book' ? 'books' : 'podcasts';
          
          await userProfileService.addPreference(authState.user.id, category, rec.title);
        }
      }
      
    } catch (error) {
      console.error('Error getting AI response:', error);
      messages = [...messages, {
        id: (Date.now() + 1).toString(),
        text: "I'm having trouble connecting to my AI services right now. I can still help you discover new things! What type of content are you interested in exploring?",
        sender: 'bot',
        timestamp: new Date()
      }];
    } finally {
      loading = false;
    }
  }
  
  async function startVoiceInput() {
    if (!voiceEnabled) {
      toastStore.add({
        type: 'error',
        title: 'Voice Not Supported',
        message: 'Voice input is not supported in your browser.'
      });
      return;
    }
    
    isListening = true;
    
    const success = await voiceService.startListening(
      (transcript) => {
        newMessage = transcript;
        isListening = false;
        sendMessage();
      },
      (error) => {
        console.error('Voice recognition error:', error);
        isListening = false;
      }
    );
    
    if (!success) {
      isListening = false;
    }
  }
  
  function stopVoiceInput() {
    voiceService.stopListening();
    isListening = false;
  }
  
  async function toggleVoiceOutput() {
    if (!voiceEnabled) {
      toastStore.add({
        type: 'error',
        title: 'Voice Not Supported',
        message: 'Voice output is not supported in your browser.'
      });
      return;
    }
    
    if (isSpeaking) {
      voiceService.stopSpeaking();
      isSpeaking = false;
    } else {
      // Speak the last bot message
      const lastBotMessage = messages.filter(m => m.sender === 'bot').pop();
      if (lastBotMessage) {
        isSpeaking = true;
        await voiceService.speak(lastBotMessage.text);
        isSpeaking = false;
      }
    }
  }
  
  function handleKeyPress(event: KeyboardEvent) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      sendMessage();
    }
  }
  
  function getTypeIcon(type: string) {
    switch (type) {
      case 'music': return Music;
      case 'movie': return Film;
      case 'book': return Book;
      case 'podcast': return Mic;
      default: return Heart;
    }
  }
</script>

<div class="flex flex-col h-[calc(100vh-4rem)] max-w-4xl mx-auto">
  <!-- Chat Header -->
  <div class="flex items-center gap-3 p-4 border-b border-border">
    <Bot class="w-6 h-6 text-primary" />
    <h2 class="text-lg font-semibold">AI Taste Companion</h2>
    {#if userProfile}
      <span class="text-sm text-muted-foreground">• Personalized</span>
    {/if}
    {#if voiceEnabled}
      <span class="text-sm text-muted-foreground">• Voice Enabled</span>
    {/if}
  </div>
  
  <!-- Messages -->
  <div class="flex-1 overflow-y-auto p-4 space-y-4">
    {#each messages as message (message.id)}
      <div class="flex {message.sender === 'user' ? 'justify-end' : 'justify-start'}">
        <div class="flex items-start gap-3 max-w-[80%]">
          {#if message.sender === 'bot'}
            <div class="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
              <Bot class="w-4 h-4 text-primary" />
            </div>
          {/if}
          <div class="bg-card border rounded-lg p-3 shadow-sm">
            <p class="text-sm">{message.text}</p>
            <p class="text-xs text-muted-foreground mt-1">
              {message.timestamp.toLocaleTimeString()}
            </p>
            
            <!-- Recommendations -->
            {#if message.recommendations && message.recommendations.length > 0}
              <div class="mt-3 pt-3 border-t border-border">
                <p class="text-xs font-medium text-muted-foreground mb-2">Recommendations:</p>
                <div class="space-y-2">
                  {#each message.recommendations as rec}
                    <div class="flex items-center gap-2 p-2 bg-muted/50 rounded">
                      <svelte:component this={getTypeIcon(rec.type)} class="w-4 h-4 text-primary" />
                      <div class="flex-1">
                        <p class="text-xs font-medium">{rec.title}</p>
                        <p class="text-xs text-muted-foreground">{rec.reason}</p>
                      </div>
                    </div>
                  {/each}
                </div>
              </div>
            {/if}
          </div>
          {#if message.sender === 'user'}
            <div class="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
              <User class="w-4 h-4 text-primary" />
            </div>
          {/if}
        </div>
      </div>
    {/each}
    
    {#if loading}
      <div class="flex justify-start">
        <div class="flex items-start gap-3 max-w-[80%]">
          <div class="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
            <Bot class="w-4 h-4 text-primary" />
          </div>
          <div class="bg-card border rounded-lg p-3 shadow-sm">
            <div class="flex items-center gap-2">
              <Loader2 class="w-4 h-4 animate-spin" />
              <span class="text-sm text-muted-foreground">AI is thinking...</span>
            </div>
          </div>
        </div>
      </div>
    {/if}
  </div>
  
  <!-- Message Input -->
  <div class="border-t border-border p-4">
    <div class="flex gap-2">
      <textarea
        bind:value={newMessage}
        on:keypress={handleKeyPress}
        placeholder="Ask me about music, movies, books, or anything you'd like to discover..."
        class="flex-1 resize-none rounded-lg border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
        rows="2"
        disabled={loading || isListening}
      ></textarea>
      
      <!-- Voice Input Button -->
      {#if voiceEnabled}
        <Button 
          on:click={isListening ? stopVoiceInput : startVoiceInput}
          variant={isListening ? 'destructive' : 'outline'}
          className="self-end"
          disabled={loading}
        >
          {#if isListening}
            <MicOff class="w-4 h-4" />
          {:else}
            <Mic class="w-4 h-4" />
          {/if}
        </Button>
      {/if}
      
      <!-- Voice Output Button -->
      {#if voiceEnabled}
        <Button 
          on:click={toggleVoiceOutput}
          variant="outline"
          className="self-end"
          disabled={loading}
        >
          {#if isSpeaking}
            <VolumeX class="w-4 h-4" />
          {:else}
            <Volume2 class="w-4 h-4" />
          {/if}
        </Button>
      {/if}
      
      <Button 
        on:click={sendMessage}
        disabled={loading || !newMessage.trim() || isListening}
        className="self-end"
      >
        <Send class="w-4 h-4" />
      </Button>
    </div>
    
    <!-- Voice Status -->
    {#if voiceEnabled}
      <div class="mt-2 text-xs text-muted-foreground">
        {#if isListening}
          <span class="flex items-center gap-1">
            <Mic class="w-3 h-3" />
            Listening... Speak now
          </span>
        {:else if isSpeaking}
          <span class="flex items-center gap-1">
            <Volume2 class="w-3 h-3" />
            Speaking...
          </span>
        {:else}
          <span class="flex items-center gap-1">
            <Mic class="w-3 h-3" />
            Click microphone to speak, or type your message
          </span>
        {/if}
      </div>
    {/if}
  </div>
</div>

// src/components/chat/ChatInterface.tsx
import { useState, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import {
  Send, 
  Mic, 
  MicOff, 
  Volume2, 
  VolumeX, 
  Loader2,
  Sparkles,
  Zap,
  Bot
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface Message {
  id: string;
  content: string;
  role: 'user' | 'assistant';
  timestamp: Date;
  type?: 'text' | 'voice';
}

interface VoiceState {
  isListening: boolean;
  isProcessing: boolean;
  isSpeaking: boolean;
  volume: number;
}

export function ChatInterface() {
  console.log('ChatInterface component rendering');
  const { user } = useAuth();
  const { toast } = useToast();
  const [messages, setMessages] = useState<Message[]>([
    { id: "1", content: "Hello! I'm your AI music assistant. What can I help you discover today?", role: "assistant", timestamp: new Date() }
  ]);
  const [inputValue, setInputValue] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [voiceState, setVoiceState] = useState<VoiceState>({
    isListening: false,
    isProcessing: false,
    isSpeaking: false,
    volume: 0.8
  });
  
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const sendMessage = async (content: string, isVoice = false) => {
    if (!content.trim() || isLoading) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      content,
      role: 'user',
      timestamp: new Date(),
      type: isVoice ? 'voice' : 'text'
    };

    setMessages(prev => [...prev, userMessage]);
    setInputValue("");
    setIsLoading(true);

    try {
      // Call Qloo recommendations endpoint
      const { data, error } = await supabase.functions.invoke('qloo-recommendations', {
        body: {
          prompt: content,
          context: 'chat_interface'
        }
      });

      if (error) throw error;

      // Get AI insights from Gemini
      const { data: insightsData, error: insightsError } = await supabase.functions.invoke('gemini-insights', {
        body: {
          recommendations: data,
          userPrompt: content,
          userProfile: null // Will be populated from user's profile
        }
      });

      if (insightsError) console.warn('Insights generation failed:', insightsError);

      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        content: insightsData?.insights || "I've processed your request and found some great recommendations! Check out the detailed results.",
        role: 'assistant',
        timestamp: new Date()
      };

      setMessages(prev => [...prev, assistantMessage]);

      // If voice input, use text-to-speech
      if (isVoice && assistantMessage.content) {
        await speakText(assistantMessage.content);
      }

    } catch (error) {
      console.error('Chat error:', error);
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        content: "I'm sorry, I'm having trouble processing your request right now. Please try again.",
        role: 'assistant',
        timestamp: new Date()
      };
      setMessages(prev => [...prev, errorMessage]);

      toast({
        title: "Chat Error",
        description: "Failed to get response. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const speakText = async (text: string) => {
    setVoiceState(prev => ({ ...prev, isSpeaking: true }));
    
    try {
      const { data, error } = await supabase.functions.invoke('text-to-speech', {
        body: {
          text: text
        }
      });

      if (error) throw error;

      // Play the audio response
      if (data?.audioContent) {
        const audio = new Audio(`data:audio/mp3;base64,${data.audioContent}`);
        audio.volume = voiceState.volume;
        audio.onended = () => setVoiceState(prev => ({ ...prev, isSpeaking: false }));
        await audio.play();
      }
    } catch (error) {
      console.error('Text-to-speech error:', error);
      setVoiceState(prev => ({ ...prev, isSpeaking: false }));
    }
  };

  const startVoiceRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      
      mediaRecorderRef.current = new MediaRecorder(stream);
      audioChunksRef.current = [];

      mediaRecorderRef.current.ondataavailable = (event) => {
        if (event.data.size > 0) {
          audioChunksRef.current.push(event.data);
        }
      };

      mediaRecorderRef.current.onstop = async () => {
        const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/wav' });
        await processVoiceInput(audioBlob);
        stream.getTracks().forEach(track => track.stop());
      };

      mediaRecorderRef.current.start();
      setVoiceState(prev => ({ ...prev, isListening: true }));

    } catch (error) {
      console.error('Voice recording error:', error);
      toast({
        title: "Microphone Error",
        description: "Could not access microphone. Please check permissions.",
        variant: "destructive",
      });
    }
  };

  const stopVoiceRecording = () => {
    if (mediaRecorderRef.current && voiceState.isListening) {
      mediaRecorderRef.current.stop();
      setVoiceState(prev => ({ ...prev, isListening: false, isProcessing: true }));
    }
  };

  const processVoiceInput = async (audioBlob: Blob) => {
    try {
      // Convert audio to text (this would typically use a speech-to-text service)
      // For now, we'll simulate transcription
      const mockTranscription = "I'd like some music recommendations based on my recent listening history";
      
      setVoiceState(prev => ({ ...prev, isProcessing: false }));
      await sendMessage(mockTranscription, true);

    } catch (error) {
      console.error('Voice processing error:', error);
      setVoiceState(prev => ({ ...prev, isProcessing: false }));
      toast({
        title: "Voice Processing Error",
        description: "Could not process voice input. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    sendMessage(inputValue);
  };

  const toggleVoice = () => {
    if (voiceState.isListening) {
      stopVoiceRecording();
    } else {
      startVoiceRecording();
    }
  };

  const toggleVolume = () => {
    setVoiceState(prev => ({ 
      ...prev, 
      volume: prev.volume > 0 ? 0 : 0.8 
    }));
  };

  return (
    <div className="flex flex-col h-[calc(100vh-4rem)] max-w-4xl mx-auto">
      {/* Header */}
      <div className="p-6 border-b border-primary/20">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-primary/20 flex items-center justify-center shimmer">
            <Bot className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-transparent bg-gradient-bubblegum bg-clip-text">
              Cultural Discovery Chat
            </h1>
            <p className="text-sm text-muted-foreground">
              Ask for personalized recommendations across music, movies, books & more
            </p>
          </div>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-6 space-y-4">
        <AnimatePresence>
          {messages.map((message) => (
            <motion.div
              key={message.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
            >
              <div className={`max-w-[70%] rounded-3xl p-4 ${
                message.role === 'user' 
                  ? 'bg-primary text-primary-foreground' 
                  : 'glass-card'
              }`}>
                <div className="flex items-start gap-2">
                  {message.role === 'assistant' && (
                    <Sparkles className="w-4 h-4 text-primary mt-1 flex-shrink-0" />
                  )}
                  {message.type === 'voice' && message.role === 'user' && (
                    <Mic className="w-4 h-4 mt-1 flex-shrink-0" />
                  )}
                  <div className="flex-1">
                    <p className="text-sm">{message.content}</p>
                    <p className="text-xs opacity-70 mt-1">
                      {message.timestamp.toLocaleTimeString()}
                    </p>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {isLoading && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex justify-start"
          >
            <div className="glass-card rounded-3xl p-4 max-w-[70%]">
              <div className="flex items-center gap-2">
                <Loader2 className="w-4 h-4 animate-spin text-primary" />
                <p className="text-sm">Generating recommendations...</p>
              </div>
            </div>
          </motion.div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input Area */}
      <div className="p-6 border-t border-primary/20">
        <form onSubmit={handleSubmit} className="flex gap-3">
          <div className="flex-1 relative">
            <Input
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              placeholder="Ask for music, movie, book, or travel recommendations..."
              className="glass-input pr-12 py-3 rounded-full"
              disabled={isLoading || voiceState.isListening}
            />
            <Button
              type="submit"
              size="sm"
              disabled={!inputValue.trim() || isLoading}
              className="absolute right-2 top-1/2 -translate-y-1/2 h-8 w-8 rounded-full p-0"
            >
              <Send className="w-4 h-4" />
            </Button>
          </div>

          {/* Voice Controls */}
          <div className="flex gap-2">
            <Button
              type="button"
              variant="outline"
              size="icon"
              onClick={toggleVolume}
              className="rounded-full glass-card"
            >
              {voiceState.volume > 0 ? (
                <Volume2 className="w-4 h-4" />
              ) : (
                <VolumeX className="w-4 h-4" />
              )}
            </Button>

            <Button
              type="button"
              variant={voiceState.isListening ? "destructive" : "outline"}
              size="icon"
              onClick={toggleVoice}
              disabled={voiceState.isProcessing || isLoading}
              className={`rounded-full ${voiceState.isListening ? 'animate-pulse' : 'glass-card'}`}
            >
              {voiceState.isProcessing ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : voiceState.isListening ? (
                <MicOff className="w-4 h-4" />
              ) : (
                <Mic className="w-4 h-4" />
              )}
            </Button>
          </div>
        </form>

        {/* Voice Status */}
        <AnimatePresence>
          {(voiceState.isListening || voiceState.isProcessing || voiceState.isSpeaking) && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="mt-3 text-center"
            >
              <div className="inline-flex items-center gap-2 text-sm text-muted-foreground">
                {voiceState.isListening && (
                  <>
                    <div className="w-2 h-2 bg-red-500 rounded-full animate-pulse" />
                    Listening...
                  </>
                )}
                {voiceState.isProcessing && (
                  <>
                    <Zap className="w-4 h-4 animate-pulse" />
                    Processing voice...
                  </>
                )}
                {voiceState.isSpeaking && (
                  <>
                    <Volume2 className="w-4 h-4 animate-pulse" />
                    Speaking...
                  </>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
