// src/pages/Privacy.tsx
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Brain, ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

export default function Privacy() {
  return (
    <div className="min-h-screen">
      {/* Header */}
      <header className="glass-strong border-b border-primary/20">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <Link to="/" className="flex items-center gap-2">
              <Brain className="w-8 h-8 text-primary" />
              <span className="text-2xl font-bold text-foreground">Cortex</span>
            </Link>
            
            <Link to="/">
              <Button variant="ghost" className="gap-2">
                <ArrowLeft className="w-4 h-4" />
                Back to Home
              </Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Content */}
      <section className="py-20 px-6">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-6">
              Privacy Policy
            </h1>
            <p className="text-xl text-muted-foreground">
              Last updated: January 2024
            </p>
          </div>

          <Card className="glass-card">
            <CardContent className="p-8 space-y-8">
              <div>
                <h2 className="text-2xl font-bold text-foreground mb-4">Information We Collect</h2>
                <p className="text-muted-foreground mb-4">
                  We collect information you provide directly to us, such as when you create an account, 
                  connect your Spotify account, or interact with our services.
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2">
                  <li>Spotify listening history and preferences</li>
                  <li>Profile information and preferences</li>
                  <li>Usage data and analytics</li>
                  <li>Communications with our service</li>
                </ul>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-foreground mb-4">How We Use Your Information</h2>
                <p className="text-muted-foreground mb-4">
                  We use the information we collect to:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2">
                  <li>Provide personalized recommendations</li>
                  <li>Match you with taste twins</li>
                  <li>Improve our AI algorithms</li>
                  <li>Send you updates and recommendations</li>
                </ul>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-foreground mb-4">Data Security</h2>
                <p className="text-muted-foreground">
                  We implement appropriate security measures to protect your personal information 
                  against unauthorized access, alteration, disclosure, or destruction.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-foreground mb-4">Your Rights</h2>
                <p className="text-muted-foreground">
                  You have the right to access, update, or delete your personal information. 
                  You can also opt out of certain communications at any time.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-foreground mb-4">Contact Us</h2>
                <p className="text-muted-foreground">
                  If you have questions about this Privacy Policy, please contact us at 
                  privacy@cortex.ai
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>
    </div>
  );
}

// src/pages/Privacy.svelte
<script lang="ts">
  import { Link } from 'svelte-routing';
</script>

<div class="min-h-screen bg-background">
  <div class="container mx-auto px-6 py-8">
    <h1 class="text-3xl font-bold mb-6">Privacy Policy</h1>
    <p class="text-muted-foreground mb-8">How we protect and handle your data.</p>
    
    <div class="max-w-4xl prose prose-gray dark:prose-invert">
      <h2>Data Collection</h2>
      <p>We collect only the data necessary to provide personalized recommendations.</p>
      
      <h2>Data Usage</h2>
      <p>Your data is used solely to improve your experience and provide better recommendations.</p>
      
      <h2>Data Protection</h2>
      <p>We implement industry-standard security measures to protect your information.</p>
      
      <h2>Your Rights</h2>
      <p>You have the right to access, modify, or delete your data at any time.</p>
    </div>
  </div>
</div>
