// src/components/ErrorBoundary.tsx
import React from 'react';

interface ErrorBoundaryState {
  hasError: boolean;
  error?: Error;
}

interface ErrorBoundaryProps {
  children: React.ReactNode;
}

class ErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundaryState> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    console.error('Error caught by boundary:', error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="min-h-screen flex items-center justify-center bg-red-50">
          <div className="text-center p-8">
            <h1 className="text-2xl font-bold text-red-600 mb-4">Something went wrong</h1>
            <p className="text-gray-600 mb-4">An error occurred while rendering the component.</p>
            <details className="text-left bg-white p-4 rounded border">
              <summary className="cursor-pointer font-semibold mb-2">Error Details</summary>
              <pre className="text-sm text-red-600 overflow-auto">
                {this.state.error?.toString()}
              </pre>
            </details>
            <button
              onClick={() => window.location.reload()}
              className="mt-4 px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700"
            >
              Reload Page
            </button>
          </div>
        </div>
      );
    }

    return this.props.children;
  }
}

export default ErrorBoundary;

// src/components/ErrorBoundary.svelte
<script lang="ts">
  let error: Error | null = null;
  
  // Simple error handling for Svelte
  function handleError(err: Error) {
    error = err;
    console.error('Error caught by boundary:', err);
  }
</script>

{#if error}
  <div class="min-h-screen flex items-center justify-center bg-background">
    <div class="text-center p-8">
      <h1 class="text-2xl font-bold mb-4 text-destructive">Something went wrong</h1>
      <p class="text-muted-foreground mb-4">We're sorry, but something unexpected happened.</p>
      <button 
        on:click={() => window.location.reload()}
        class="px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90"
      >
        Reload Page
      </button>
      {#if error.message}
        <details class="mt-4 text-left">
          <summary class="cursor-pointer text-sm text-muted-foreground">Error Details</summary>
          <pre class="mt-2 text-xs bg-muted p-2 rounded overflow-auto">{error.message}</pre>
        </details>
      {/if}
    </div>
  </div>
{:else}
  <slot />
{/if}
