// src/App.tsx
import React from "react";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { ThemeProvider } from "next-themes";
import ErrorBoundary from "@/components/ErrorBoundary";
import Dashboard from "./pages/Dashboard";
import NotFound from "./pages/NotFound";
import { AuthPage } from "./components/auth/AuthPage";
import AuthCallback from "./pages/AuthCallback";
import Onboarding from "./pages/Onboarding";
import TasteProfile from "./pages/TasteProfile";
import Recommendations from "./pages/Recommendations";
import SpotifySync from "./pages/SpotifySync";
import TasteTwins from "./pages/TasteTwins";
import Saved from "./pages/Saved";
import Settings from "./pages/Settings";
import Landing from "./pages/Landing";
import About from "./pages/About";
import Terms from "./pages/Terms";
import Privacy from "./pages/Privacy";
import DataUsage from "./pages/DataUsage";
import MediaSearch from "./pages/MediaSearch";

const queryClient = new QueryClient();

const App = () => {
  const [isLoaded, setIsLoaded] = React.useState(false);

  React.useEffect(() => {
    // Mark as loaded after a short delay to ensure styles are applied
    const timer = setTimeout(() => setIsLoaded(true), 100);
    return () => clearTimeout(timer);
  }, []);

  return (
    <ErrorBoundary>
      <div className={`min-h-screen ${isLoaded ? 'loaded' : 'loading'}`}>
        <QueryClientProvider client={queryClient}>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <TooltipProvider>
              <Toaster />
              <Sonner />
              <BrowserRouter>
                <Routes>
                  <Route path="/" element={<Landing />} />
                  <Route path="/dashboard" element={<Dashboard />} />
                  <Route path="/profile" element={<TasteProfile />} />
                  <Route path="/recommendations" element={<Recommendations />} />
                  <Route path="/spotify" element={<SpotifySync />} />
                  <Route path="/friends" element={<TasteTwins />} />
                  <Route path="/saved" element={<Saved />} />
                  <Route path="/settings" element={<Settings />} />
                  <Route path="/auth" element={<AuthPage />} />
                  <Route path="/auth/callback" element={<AuthCallback />} />
                  <Route path="/onboarding" element={<Onboarding />} />
                  <Route path="/about" element={<About />} />
                  <Route path="/terms" element={<Terms />} />
                  <Route path="/privacy" element={<Privacy />} />
                  <Route path="/data-usage" element={<DataUsage />} />
                  <Route path="/media" element={<MediaSearch />} />
                  {/* ADD ALL CUSTOM ROUTES ABOVE THE CATCH-ALL "*" ROUTE */}
                  <Route path="*" element={<NotFound />} />
                </Routes>
              </BrowserRouter>
            </TooltipProvider>
          </ThemeProvider>
        </QueryClientProvider>
      </div>
    </ErrorBoundary>
  );
};

export default App;

// src/App.svelte
<script lang="ts">
  import { Router, Link, Route } from 'svelte-routing';
  import { onMount } from 'svelte';
  
  // Import pages
  import Dashboard from './pages/Dashboard.svelte';
  import Landing from './pages/Landing.svelte';
  import NotFound from './pages/NotFound.svelte';
  import AuthPage from './components/auth/AuthPage.svelte';
  import AuthCallback from './pages/AuthCallback.svelte';
  import Onboarding from './pages/Onboarding.svelte';
  import TasteProfile from './pages/TasteProfile.svelte';
  import Recommendations from './pages/Recommendations.svelte';
  import SpotifySync from './pages/SpotifySync.svelte';
  import TasteTwins from './pages/TasteTwins.svelte';
  import Saved from './pages/Saved.svelte';
  import Settings from './pages/Settings.svelte';
  import About from './pages/About.svelte';
  import Terms from './pages/Terms.svelte';
  import Privacy from './pages/Privacy.svelte';
  import DataUsage from './pages/DataUsage.svelte';
  import MediaSearch from './pages/MediaSearch.svelte';

  // Import components
  import Toaster from './components/ui/toaster/Toaster.svelte';
  import Sonner from './components/ui/sonner/Sonner.svelte';
  import TooltipProvider from './components/ui/tooltip/TooltipProvider.svelte';
  import ErrorBoundary from './components/ErrorBoundary.svelte';
  import ThemeProvider from './components/ui/theme/ThemeProvider.svelte';

  let isLoaded = false;

  onMount(() => {
    // Mark as loaded after a short delay to ensure styles are applied
    const timer = setTimeout(() => isLoaded = true, 100);
    return () => clearTimeout(timer);
  });
</script>

<ErrorBoundary>
  <div class="min-h-screen {isLoaded ? 'loaded' : 'loading'}">
    <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
      <TooltipProvider>
        <Toaster />
        <Sonner />
        <Router>
          <Route path="/" component={Landing} />
          <Route path="/dashboard" component={Dashboard} />
          <Route path="/profile" component={TasteProfile} />
          <Route path="/recommendations" component={Recommendations} />
          <Route path="/spotify" component={SpotifySync} />
          <Route path="/friends" component={TasteTwins} />
          <Route path="/saved" component={Saved} />
          <Route path="/settings" component={Settings} />
          <Route path="/auth" component={AuthPage} />
          <Route path="/auth/callback" component={AuthCallback} />
          <Route path="/onboarding" component={Onboarding} />
          <Route path="/about" component={About} />
          <Route path="/terms" component={Terms} />
          <Route path="/privacy" component={Privacy} />
          <Route path="/data-usage" component={DataUsage} />
          <Route path="/media" component={MediaSearch} />
          <Route path="*" component={NotFound} />
        </Router>
      </TooltipProvider>
    </ThemeProvider>
  </div>
</ErrorBoundary>

<style>
  .loading {
    opacity: 0;
    transition: opacity 0.3s ease-in-out;
  }
  
  .loaded {
    opacity: 1;
  }
</style>
